ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends \
      fish jq neovim tmux ripgrep starship wl-clipboard \
 && rm -rf /var/lib/apt/lists/*

COPY dotfiles/ /usr/local/share/box-template/dotfiles/
COPY initialize-home /usr/local/bin/box-initialize-home
RUN chmod 0755 /usr/local/bin/box-initialize-home

ENTRYPOINT ["/usr/local/bin/box-initialize-home"]
