FROM archlinux:latest

ARG USER_UID=1000
ARG USER_GID=1000

RUN pacman -Syu --noconfirm \
        bash \
        bat \
        base-devel \
        ca-certificates \
        curl \
        eza \
        fd \
        fish \
        fzf \
        git \
        jq \
        neovim \
        pkgconf \
        python \
        python-pipx \
        ripgrep \
        starship \
        tar \
        tmux \
        unzip \
        wget \
        wl-clipboard \
        zip \
        zoxide \
    && groupadd --gid "${USER_GID}" developer \
    && useradd --uid "${USER_UID}" --gid developer --create-home --shell /usr/bin/fish developer \
    && sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && locale-gen \
    && pacman -Scc --noconfirm

ENV LANG=en_US.UTF-8
ENV HOME=/home/developer

USER developer
WORKDIR /home/developer
CMD ["fish", "--login"]
